language: node_js
notifications:
  email: false
before_install:
  - rvm install 2.4.0
install:
  - gem install awesome_bot
before_script:
  - echo $GH_TOKEN
script:
  - this-wont-run
after_success:
  - cd build
  - sh build.sh
  - sh deploy.sh
