name: "Validate links"

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  FORMAT_FILE: README.md

jobs:
  test:
    name: 'Validate README.md'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate all links from README.md
        run: build/validate_links.sh ${FORMAT_FILE}
